compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  zero3_init_flag: true
  deepspeed_config_file: config/zero_stage3_offload_config.json
distributed_type: DEEPSPEED
fsdp_config: {}
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 2
use_cpu: false